# ./cloudbuild.yaml

steps:
    - name: node:18 # [A]
      entrypoint: npm
      args: ['install']
    - name: node:18 # [B]
      entrypoint: npm
      args: ['run', 'build']
      env:
          - 'GOOGLE_MAP_API_KEY=AIzaSyC0ONrdKLPauqnBEbRDUegy8Yn2_5SNlxU'
          - 'API_BASE_URL=https://autosuggest-ssr.el.r.appspot.com/'
    - name: gcr.io/cloud-builders/gsutil # [C]
      args: ['-m', 'rsync', '-r', '-c', '-d', './dist', 'gs://autosuggest-ssr/dist']
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # [D]
      entrypoint: 'bash'
      args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
      timeout: '1600s'
